# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\big_root_system\ui\img_capature_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImgCaptureWidget(object):
    def setupUi(self, ImgCaptureWidget):
        ImgCaptureWidget.setObjectName("ImgCaptureWidget")
        ImgCaptureWidget.resize(1808, 906)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(ImgCaptureWidget)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_img1 = QtWidgets.QLabel(ImgCaptureWidget)
        self.label_img1.setStyleSheet("font-family: \'微软雅黑\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.label_img1.setObjectName("label_img1")
        self.verticalLayout_12.addWidget(self.label_img1)
        self.graphicsView_img1 = QtWidgets.QGraphicsView(ImgCaptureWidget)
        self.graphicsView_img1.setMinimumSize(QtCore.QSize(601, 851))
        self.graphicsView_img1.setObjectName("graphicsView_img1")
        self.verticalLayout_12.addWidget(self.graphicsView_img1)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_img2 = QtWidgets.QLabel(ImgCaptureWidget)
        self.label_img2.setStyleSheet("font-family: \'微软雅黑\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.label_img2.setObjectName("label_img2")
        self.verticalLayout_11.addWidget(self.label_img2)
        self.graphicsView_img2 = QtWidgets.QGraphicsView(ImgCaptureWidget)
        self.graphicsView_img2.setMinimumSize(QtCore.QSize(601, 851))
        self.graphicsView_img2.setObjectName("graphicsView_img2")
        self.verticalLayout_11.addWidget(self.graphicsView_img2)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_arduino = QtWidgets.QLabel(ImgCaptureWidget)
        self.label_arduino.setStyleSheet("font-family: \'Times New Roman\';\n"
"font-size: 12px;\n"
"font-weight: bold;")
        self.label_arduino.setObjectName("label_arduino")
        self.verticalLayout_4.addWidget(self.label_arduino)
        self.cb_arduino = QtWidgets.QComboBox(ImgCaptureWidget)
        self.cb_arduino.setMinimumSize(QtCore.QSize(100, 30))
        self.cb_arduino.setStyleSheet("font-family: \'Times New Roman\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.cb_arduino.setObjectName("cb_arduino")
        self.cb_arduino.addItem("")
        self.cb_arduino.addItem("")
        self.cb_arduino.addItem("")
        self.cb_arduino.addItem("")
        self.cb_arduino.addItem("")
        self.cb_arduino.addItem("")
        self.cb_arduino.addItem("")
        self.cb_arduino.addItem("")
        self.verticalLayout_4.addWidget(self.cb_arduino)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_scanner = QtWidgets.QLabel(ImgCaptureWidget)
        self.label_scanner.setStyleSheet("font-family: \'Times New Roman\';\n"
"font-size: 12px;\n"
"font-weight: bold;")
        self.label_scanner.setObjectName("label_scanner")
        self.verticalLayout_5.addWidget(self.label_scanner)
        self.cb_scanner = QtWidgets.QComboBox(ImgCaptureWidget)
        self.cb_scanner.setMinimumSize(QtCore.QSize(100, 30))
        self.cb_scanner.setStyleSheet("font-family: \'Times New Roman\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.cb_scanner.setObjectName("cb_scanner")
        self.cb_scanner.addItem("")
        self.cb_scanner.addItem("")
        self.cb_scanner.addItem("")
        self.cb_scanner.addItem("")
        self.cb_scanner.addItem("")
        self.cb_scanner.addItem("")
        self.cb_scanner.addItem("")
        self.cb_scanner.addItem("")
        self.verticalLayout_5.addWidget(self.cb_scanner)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_serial_connect = QtWidgets.QPushButton(ImgCaptureWidget)
        self.btn_serial_connect.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_serial_connect.setFont(font)
        self.btn_serial_connect.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \'微软雅黑\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.btn_serial_connect.setObjectName("btn_serial_connect")
        self.horizontalLayout_4.addWidget(self.btn_serial_connect)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_forward = QtWidgets.QPushButton(ImgCaptureWidget)
        self.btn_forward.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_forward.setStyleSheet("background-color: rgb(0, 85, 255);color: white;\n"
"font-family: \'Times New Roman\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.btn_forward.setObjectName("btn_forward")
        self.horizontalLayout_5.addWidget(self.btn_forward)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(ImgCaptureWidget)
        self.btn_back.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_back.setStyleSheet("font-family: \'Times New Roman\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_5.addWidget(self.btn_back)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btn_stop = QtWidgets.QPushButton(ImgCaptureWidget)
        self.btn_stop.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_stop.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font-family: \'Times New Roman\';\n"
"font-size: 16px;\n"
"font-weight: bold;")
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_5.addWidget(self.btn_stop)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_log = QtWidgets.QLabel(ImgCaptureWidget)
        self.label_log.setObjectName("label_log")
        self.verticalLayout_10.addWidget(self.label_log)
        self.tb_log = QtWidgets.QTextBrowser(ImgCaptureWidget)
        self.tb_log.setMinimumSize(QtCore.QSize(560, 660))
        self.tb_log.setObjectName("tb_log")
        self.verticalLayout_10.addWidget(self.tb_log)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout)

        self.retranslateUi(ImgCaptureWidget)
        QtCore.QMetaObject.connectSlotsByName(ImgCaptureWidget)

    def retranslateUi(self, ImgCaptureWidget):
        _translate = QtCore.QCoreApplication.translate
        ImgCaptureWidget.setWindowTitle(_translate("ImgCaptureWidget", "Form"))
        self.label_img1.setText(_translate("ImgCaptureWidget", "图片显示：第一张"))
        self.label_img2.setText(_translate("ImgCaptureWidget", "图片显示：第二张"))
        self.label_arduino.setText(_translate("ImgCaptureWidget", "Arduino串口设置"))
        self.cb_arduino.setCurrentText(_translate("ImgCaptureWidget", "com7"))
        self.cb_arduino.setItemText(0, _translate("ImgCaptureWidget", "com7"))
        self.cb_arduino.setItemText(1, _translate("ImgCaptureWidget", "com1"))
        self.cb_arduino.setItemText(2, _translate("ImgCaptureWidget", "com2"))
        self.cb_arduino.setItemText(3, _translate("ImgCaptureWidget", "com3"))
        self.cb_arduino.setItemText(4, _translate("ImgCaptureWidget", "com4"))
        self.cb_arduino.setItemText(5, _translate("ImgCaptureWidget", "com5"))
        self.cb_arduino.setItemText(6, _translate("ImgCaptureWidget", "com6"))
        self.cb_arduino.setItemText(7, _translate("ImgCaptureWidget", "com8"))
        self.label_scanner.setText(_translate("ImgCaptureWidget", "扫描器串口设置"))
        self.cb_scanner.setItemText(0, _translate("ImgCaptureWidget", "com7"))
        self.cb_scanner.setItemText(1, _translate("ImgCaptureWidget", "com1"))
        self.cb_scanner.setItemText(2, _translate("ImgCaptureWidget", "com2"))
        self.cb_scanner.setItemText(3, _translate("ImgCaptureWidget", "com3"))
        self.cb_scanner.setItemText(4, _translate("ImgCaptureWidget", "com4"))
        self.cb_scanner.setItemText(5, _translate("ImgCaptureWidget", "com5"))
        self.cb_scanner.setItemText(6, _translate("ImgCaptureWidget", "com6"))
        self.cb_scanner.setItemText(7, _translate("ImgCaptureWidget", "com8"))
        self.btn_serial_connect.setText(_translate("ImgCaptureWidget", "确认串口连接"))
        self.btn_forward.setText(_translate("ImgCaptureWidget", "前进"))
        self.btn_back.setText(_translate("ImgCaptureWidget", "后退"))
        self.btn_stop.setText(_translate("ImgCaptureWidget", "停止"))
        self.label_log.setText(_translate("ImgCaptureWidget", "当前处理信息"))
